<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>programacion2.Clase02.Condicionantes</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Victor\" />
  </ItemGroup>

</Project>
